In [168]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier


# Question 1 iris dataset

In [169]:
names=['sepal-length','sepal-width','petal-length','petal-width','class']
dataset=pd.read_csv('iris.data',names=names)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [170]:
dataset.shape

(150, 5)

In [171]:
dataset.groupby('class').size()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [172]:
array=dataset.values
X=array[:,0:4]
Y=array[:,4]
t_size=0.20
seed=7
X_train,X_test,Y_train , Y_test =train_test_split(X,Y,test_size=t_size,
                                                  random_state=seed)


In [173]:
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)
predictions=knn.predict(X_test)
print(accuracy_score(Y_test,predictions))
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))


0.9
[[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [174]:
for i in range(1,10):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,Y_train)
    predictions=knn.predict(X_test)

    print('k=',i,', Accuracy=',accuracy_score(Y_test,predictions))

    

k= 1 , Accuracy= 0.9
k= 2 , Accuracy= 0.9333333333333333
k= 3 , Accuracy= 0.9
k= 4 , Accuracy= 0.9333333333333333
k= 5 , Accuracy= 0.9
k= 6 , Accuracy= 0.8666666666666667
k= 7 , Accuracy= 0.8666666666666667
k= 8 , Accuracy= 0.9
k= 9 , Accuracy= 0.9


In [176]:

for i in range(1,10):
    X_train,X_test,Y_train , Y_test =train_test_split(X,Y,test_size=t_size,
                                                      random_state=i)
    knn=KNeighborsClassifier()
    knn.fit(X_train,Y_train)
    predictions=knn.predict(X_test)
    print('seed=',i,', Accuracy=',accuracy_score(Y_test,predictions))
    
    

seed= 1 , Accuracy= 1.0
seed= 2 , Accuracy= 1.0
seed= 3 , Accuracy= 0.9666666666666667
seed= 4 , Accuracy= 0.9666666666666667
seed= 5 , Accuracy= 0.9333333333333333
seed= 6 , Accuracy= 0.9666666666666667
seed= 7 , Accuracy= 0.9
seed= 8 , Accuracy= 0.9
seed= 9 , Accuracy= 1.0


# Question 2 Occupacy data set builtin libraries

In [190]:
names = ['date','Temperature', 'Humidity', 'Light', 'CO2', 'HumidityRatio','Occupancy']
dataset = pd.read_csv('datatraining.txt', names=names,header=0)
dataset.drop(dataset.index[0])
dataset=dataset.drop(['date'],axis=1)
dataset



Temperature  Humidity  Light         CO2  HumidityRatio  Occupancy
1           23.18   27.2720  426.0  721.250000       0.004793          1
2           23.15   27.2675  429.5  714.000000       0.004783          1
3           23.15   27.2450  426.0  713.500000       0.004779          1
4           23.15   27.2000  426.0  708.250000       0.004772          1
5           23.10   27.2000  426.0  704.500000       0.004757          1
...           ...       ...    ...         ...            ...        ...
8139        21.05   36.0975  433.0  787.250000       0.005579          1
8140        21.05   35.9950  433.0  789.500000       0.005563          1
8141        21.10   36.0950  433.0  798.500000       0.005596          1
8142        21.10   36.2600  433.0  820.333333       0.005621          1
8143        21.10   36.2000  447.0  821.000000       0.005612          1

[8143 rows x 6 columns]

In [193]:
#Test Set 1

dataset2 = pd.read_csv('datatest.txt', names=names,header=0)
dataset2.drop(dataset2.index[0])
dataset2=dataset2.drop(['date'],axis=1)
print("Test Set 1")
print(dataset2)

#Test Set 2
dataset3 = pd.read_csv('datatest2.txt', names=names,header=0)
dataset3.drop(dataset3.index[0])
dataset3=dataset3.drop(['date'],axis=1)
print("Test Set 2")
print(dataset3)

Test Set 1
      Temperature   Humidity       Light          CO2  HumidityRatio  \
140     23.700000  26.272000  585.200000   749.200000       0.004764   
141     23.718000  26.290000  578.400000   760.400000       0.004773   
142     23.730000  26.230000  572.666667   769.666667       0.004765   
143     23.722500  26.125000  493.750000   774.750000       0.004744   
144     23.754000  26.200000  488.600000   779.000000       0.004767   
...           ...        ...         ...          ...            ...   
2800    24.290000  25.700000  808.000000  1150.250000       0.004829   
2801    24.330000  25.736000  809.800000  1129.200000       0.004848   
2802    24.330000  25.700000  817.000000  1125.800000       0.004841   
2803    24.356667  25.700000  813.000000  1123.000000       0.004849   
2804    24.408333  25.681667  798.000000  1124.000000       0.004860   

      Occupancy  
140           1  
141           1  
142           1  
143           1  
144           1  
...         ... 

In [194]:
print(dataset.shape)
print(dataset2.shape)
print(dataset3.shape)


(8143, 6)
(2665, 6)
(9752, 6)


In [196]:
array = dataset.values
X_train = array[:,0:5]
y_train = array[:,5]

array = dataset2.values
X_test=  array[:,0:5]
y_test = array[:,5]

array = dataset3.values
X2_test=  array[:,0:5]
y2_test = array[:,5]

In [198]:
#Dataset 1
knn = KNeighborsClassifier() 
knn.fit(X_train, y_train) 
predictions = knn.predict(X_test) 
print(accuracy_score(y_test, predictions)) 
print(confusion_matrix(y_test, predictions)) 
print(classification_report(y_test, predictions))


0.9425891181988743
[[1645   48]
 [ 105  867]]
              precision    recall  f1-score   support

         0.0       0.94      0.97      0.96      1693
         1.0       0.95      0.89      0.92       972

    accuracy                           0.94      2665
   macro avg       0.94      0.93      0.94      2665
weighted avg       0.94      0.94      0.94      2665



In [200]:
#Dataset 2
 
predictions = knn.predict(X2_test) 
print(accuracy_score(y2_test, predictions)) 
print(confusion_matrix(y2_test, predictions)) 
print(classification_report(y2_test, predictions))


0.9621616078753076
[[7385  318]
 [  51 1998]]
              precision    recall  f1-score   support

         0.0       0.99      0.96      0.98      7703
         1.0       0.86      0.98      0.92      2049

    accuracy                           0.96      9752
   macro avg       0.93      0.97      0.95      9752
weighted avg       0.97      0.96      0.96      9752



In [201]:
print("Changing the value of neighbours\n")
print("Test set 1\n")
#on test set 1
for i in range(1,10):
  #k value changed
  knn = KNeighborsClassifier(i) 
  knn.fit(X_train, y_train) 
  predictions = knn.predict(X_test) 
  print("K= {0}, Accuracy = {1}".format(i,accuracy_score(y_test, predictions))) 

print("Test set 2\n")

#on test set 2
for i in range(1,10):
  #k value changed
  knn = KNeighborsClassifier(i) 
  knn.fit(X_train, y_train) 
  predictions = knn.predict(X2_test) 
  print("K= {0}, Accuracy = {1}".format(i,accuracy_score(y2_test, predictions))) 

Changing the value of neighbours

Test set 1

K= 1, Accuracy = 0.9365853658536586
K= 2, Accuracy = 0.9230769230769231
K= 3, Accuracy = 0.9350844277673546
K= 4, Accuracy = 0.9275797373358349
K= 5, Accuracy = 0.9425891181988743
K= 6, Accuracy = 0.9324577861163227
K= 7, Accuracy = 0.9609756097560975
K= 8, Accuracy = 0.9549718574108818
K= 9, Accuracy = 0.9617260787992495
Test set 2

K= 1, Accuracy = 0.9502666119770303
K= 2, Accuracy = 0.9525225594749795
K= 3, Accuracy = 0.9579573420836751
K= 4, Accuracy = 0.9539581624282198
K= 5, Accuracy = 0.9621616078753076
K= 6, Accuracy = 0.9628794093519278
K= 7, Accuracy = 0.9649302707136997
K= 8, Accuracy = 0.9658531583264971
K= 9, Accuracy = 0.9656480721903199


# Question 3 iris dataset

In [206]:
import numpy as np

In [207]:
names=['sepal-length','sepal-width','petal-length','petal-width','class']
dataset=pd.read_csv('iris.data',names=names)
training=dataset[0:120]
testing =dataset[121:]
training=training.drop(columns=['class'])
testing =testing.drop(columns=['class'])
classifier="class"


In [208]:
def distance(p1,p2):
    i=0
    s=0
    while(i<len(p1)):
        diff=p1[i]-p2[i]
        t=diff*diff
        t=t/(p1[i]+p2[i])
        s=s+t
        i+=1
    return s

    
def knn(k,vals):
    for i in vals:
        min=vals[i]
        mini=i
        break
    selected=[]
    m=0
    while(m<k):
        for i in vals:
            if(min>vals[i]):
                min=vals[i]
                mini=i
       
        selected.append(mini)
        del vals[mini]
        for i in vals:
            min=vals[i]
            mini=i
            break
        
        m+=1
    prediction={}
    for i in selected:
        if(dataset[classifier][i] in prediction):
            prediction[dataset[classifier][i]]+=1
        else:
            prediction[dataset[classifier][i]]=1
    max=-1
    
    for i in prediction:
        if(max<prediction[i]):
            maxi=i
            max=prediction[i]
    return maxi
    
        

def knnModel(k):
    correctlyPredicted=0
    totalPredicted=0
    distances={}
    for index, row in testing.iterrows():
        distances={}
        a=np.array(row)
        for index1,row1 in training.iterrows():
            b=np.array(row1)
            dist=distance(a,b)
            distances[index1]=dist
        predicted=knn(k,distances)
        if(dataset[classifier][index]==predicted):
            correctlyPredicted+=1
        totalPredicted+=1

    #     print('original : ',dataset[classifier][index],'predicted: ',predicted)
    accuracy=correctlyPredicted/totalPredicted
    print(accuracy*100,'%')

for i in range(1,10):
    print('for k = ',i)
    knnModel(i)

for k =  1
79.3103448275862 %
for k =  2
79.3103448275862 %
for k =  3
82.75862068965517 %
for k =  4
79.3103448275862 %
for k =  5
82.75862068965517 %
for k =  6
82.75862068965517 %
for k =  7
82.75862068965517 %
for k =  8
86.20689655172413 %
for k =  9
86.20689655172413 %


# Question 3 Occupancy dataset 1

In [166]:

testset=pd.read_csv('datatest.txt')
testset=testset.drop(columns=['date'])
# test1
# test2=pd.read_csv('datatest.txt')
# test2=test2.drop(columns=['date'])
# test2

dataset=pd.read_csv('datatraining.txt')
dataset=dataset.drop(columns=['date'])

training=dataset

testing =testset

classifier="Occupancy"
training=training.drop(columns=[classifier])
testing =testing.drop(columns=[classifier])

k=5

In [214]:
def distance(p1,p2):
    i=0
    s=0
    while(i<len(p1)):
        diff=p1[i]-p2[i]
        t=diff*diff
        t=t/(p1[i]+p2[i])
        s=s+t
        i+=1
    return s

    
def knn(k,vals):
    for i in vals:
        min=vals[i]
        mini=i
        break
    selected=[]
    m=0
    while(m<k):
        for i in vals:
            if(min>vals[i]):
                min=vals[i]
                mini=i
       
        selected.append(mini)
        del vals[mini]
        for i in vals:
            min=vals[i]
            mini=i
            break
        
        m+=1
    prediction={}
    for i in selected:
        if(dataset[classifier][i] in prediction):
            prediction[dataset[classifier][i]]+=1
        else:
            prediction[dataset[classifier][i]]=1
    max=-1
    
    for i in prediction:
        if(max<prediction[i]):
            maxi=i
            max=prediction[i]
    return maxi
    
        

def knnModel(k):
    correctlyPredicted=0
    totalPredicted=0
    distances={}
    for index, row in testing.iterrows():
        distances={}
        a=np.array(row)
        for index1,row1 in training.iterrows():
            b=np.array(row1)
            dist=distance(a,b)
            distances[index1]=dist
        predicted=knn(k,distances)
        if(dataset[classifier][index]==predicted):
            correctlyPredicted+=1
        totalPredicted+=1

        print('original : ',dataset[classifier][index],'predicted: ',predicted)
    accuracy=correctlyPredicted/totalPredicted
    print(accuracy*100,'%')

for i in range(1,10):
    print('for k = ',i)
    knnModel(i)

for k =  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1


KeyboardInterrupt: 

# Question 3 Occupancy dataset 2

In [211]:
# test1
# testset=pd.read_csv('datatest.txt')
# testset=testset.drop(columns=['date'])

# test2

testset=pd.read_csv('datatest2.txt')
testset=testset.drop(columns=['date'])

dataset=pd.read_csv('datatraining.txt')
dataset=dataset.drop(columns=['date'])

training=dataset

testing =testset

classifier="Occupancy"
training=training.drop(columns=[classifier])
testing =testing.drop(columns=[classifier])

k=5

In [213]:
def distance(p1,p2):
    i=0
    s=0
    while(i<len(p1)):
        diff=p1[i]-p2[i]
        t=diff*diff
        t=t/(p1[i]+p2[i])
        s=s+t
        i+=1
    return s

    
def knn(k,vals):
    for i in vals:
        min=vals[i]
        mini=i
        break
    selected=[]
    m=0
    while(m<k):
        for i in vals:
            if(min>vals[i]):
                min=vals[i]
                mini=i
       
        selected.append(mini)
        del vals[mini]
        for i in vals:
            min=vals[i]
            mini=i
            break
        
        m+=1
    prediction={}
    for i in selected:
        if(dataset[classifier][i] in prediction):
            prediction[dataset[classifier][i]]+=1
        else:
            prediction[dataset[classifier][i]]=1
    max=-1
    
    for i in prediction:
        if(max<prediction[i]):
            maxi=i
            max=prediction[i]
    return maxi
    
        

def knnModel(k):
    correctlyPredicted=0
    totalPredicted=0
    distances={}
    for index, row in testing.iterrows():
        distances={}
        a=np.array(row)
        for index1,row1 in training.iterrows():
            b=np.array(row1)
            dist=distance(a,b)
            distances[index1]=dist
        predicted=knn(k,distances)
        if(dataset[classifier][index]==predicted):
            correctlyPredicted+=1
        totalPredicted+=1
        print('original : ',dataset[classifier][index],'predicted: ',predicted)

    accuracy=correctlyPredicted/totalPredicted

    print(accuracy*100,'%')

for i in range(1,10):
    print('for k = ',i)
    knnModel(i)

for k =  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1
original :  1 predicted:  1


KeyboardInterrupt: 